config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('movies/', include('movies.urls')),
    path('musics/', include('musics.urls')),
    path('sports/', include('sports.urls')),
    path('travels/', include('travels.urls')),
]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'


urlpatterns = [
    path('list/', views.movie_list, name='list'),
    path('create/', views.create_movie, name='create'),
    path('update/<int:movie_id>/', views.update_movie, name='update'),
    path('detail/<int:movie_id>/', views.movie_detail, name='detail'),
    path('delete/<int:movie_id>/', views.movie_delete, name='delete'),
]

movies/models.py
from django.db import models
from django.shortcuts import reverse


class Movie(models.Model):
    name = models.CharField(max_length=100)
    director = models.CharField(max_length=50)
    year = models.PositiveIntegerField()
    genre = models.CharField(max_length=50)


    def get_detail_url(self):
        return reverse('movies:detail', args=[self.pk])


    def get_delete_url(self):
        return reverse('movies:delete', args=[self.pk])


    def get_update_url(self):
        return reverse('movies:update', args=[self.pk])

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie


def home(request):
    return render(request, 'index.html')


def movie_list(request):
    movies = Movie.objects.all()
    ctx = {'movies': movies}
    return render(request, 'movies/list.html', ctx)


def create_movie(request):
    if request.method == "POST":
        name = request.POST.get('name')
        director = request.POST.get('director')
        year = request.POST.get('year')
        genre = request.POST.get('genre')
        if name and director and year and genre:
            Movie.objects.create(
                name=name,
                director=director,
                year=year,
                genre=genre,
            )
            return redirect('movies:list')
    return render(request, 'movies/form.html')


def update_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.method == "POST":
        name = request.POST.get('name')
        director = request.POST.get('director')
        year = request.POST.get('year')
        genre = request.POST.get('genre')
        if name and director and year and genre:
            movie.name = name
            movie.director = director
            movie.year = year
            movie.genre = genre
            movie.save()
            return redirect(movie.get_detail_url())
    ctx = {'movie': movie}
    return render(request, 'movies/form.html', ctx)


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    ctx = {'movie': movie}
    return render(request, 'movies/detail.html', ctx)


def movie_delete(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    movie.delete()
    return redirect('movies:list')

templates/movies/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{movie.name}}</title>
</head>
<body>
    <h1>{{movie.name}}</h1>

    <h3>Director: {{movie.director}}</h3>
    <h3>Release Year: {{movie.year}}</h3>
    <h3>Genre: {{movie.genre}}</h3>

    <button>
        <a href="{{movie.get_update_url}}">Update</a>
    </button>

    <button>
        <a href="{% url 'movies:delete' movie_id=movie.pk %}">Delete</a>
    </button>

    <button>
        <a href="{% url 'movies:list' %}">Back to List</a>
    </button>

</body>
</html>

templates/movies/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if movie %} Update Movie {% else %} Create Movie {% endif %}</title>
</head>
<body>
    <h1>{% if movie %} Update Movie {% else %} Create Movie {% endif %}</h1>
    {% if movie %}
        <button>
            <a href="{{ movie.get_detail_url }}" >Back to Detail</a>
        </button><br><br>
    {% else %}
        <button>
            <a href="{% url 'movies:list' %}">Back to List</a>
        </button><br><br>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <label for="name">Title:</label><br>
        <input type="text" name="name" id="name" value="{{ movie.name }}"><br><br>

        <label for="director">Director:</label><br>
        <input type="text" name="director" id="director" value="{{ movie.director }}"><br><br>

        <label for="year">Release Year:</label><br>
        <input type="number" name="year" id="year" min="1990" max="2050" value="{{ movie.year }}"><br><br>


        <label for="genre">Genre:</label><br>
        <input type="text" name="genre" id="genre" value="{{ movie.genre }}"><br><br>

        <button type="submit">{% if movie %} Update {% else %} Create {% endif %}</button>
    </form>
</body>
</html>

templates/movies/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Movies</title>
</head>
<body>
    <h1>List of Movies</h1>

    <button>
        <a href="{% url 'home' %}">Back to Home</a>
    </button>
    <button>
        <a href="{% url 'movies:create' %}">Add a New Group</a>
    </button>

    {% for movie in movies %}
        <a href="{% url 'movies:detail' movie_id=movie.pk %}"><h3>{{ movie.name }}</h3></a>
    {% empty %}
        <h3>No Movie</h3>
    {% endfor %}

</body>
</html>