config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('movies/', include('movies.urls')),
    path('musics/', include('musics.urls')),
    path('sports/', include('sports.urls')),
    path('travels/', include('travels.urls')),
]

sports/urls.py
from django.urls import path
from . import views


app_name = 'sports'


urlpatterns = [
    path('list/', views.sport_list, name='sport_list'),
    path('create/', views.create_sport, name='create_sport'),
    path('update/<int:sport_id>/', views.update_sport, name='update_sport'),
    path('detail/<int:sport_id>/', views.sport_detail, name='sport_detail'),
    path('delete/<int:sport_id>/', views.sport_delete, name='sport_delete'),
]

sports/models.py
from django.db import models
from django.shortcuts import reverse


class Sport(models.Model):
    name = models.CharField(max_length=100)
    location = models.TextField()
    date = models.DateField()
    sport_type = models.CharField(max_length=50)


    def get_detail_url(self):
        return reverse('sports:sport_detail', args=[self.pk])


    def get_delete_url(self):
        return reverse('sports:sport_delete', args=[self.pk])


    def get_update_url(self):
        return reverse('sports:update_sport', args=[self.pk])

sports/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Sport


def sport_list(request):
    sports = Sport.objects.all()
    ctx = {'sports': sports}
    return render(request, 'sports/list.html', ctx)


def create_sport(request):
    if request.method == "POST":
        name = request.POST.get('name')
        location = request.POST.get('location')
        date = request.POST.get('date')
        sport_type = request.POST.get('sport_type')
        if name and location and date and sport_type:
            Sport.objects.create(
                name=name,
                location=location,
                date=date,
                sport_type=sport_type,
            )
            return redirect('sports:sport_list')
    return render(request, 'sports/form.html')


def update_sport(request, sport_id):
    sport = get_object_or_404(Sport, pk=sport_id)

    if request.method == "POST":
        name = request.POST.get('name')
        location = request.POST.get('location')
        date = request.POST.get('date')
        sport_type = request.POST.get('sport_type')

        if location and name and date and sport_type:
            sport.name = name
            sport.location = location
            sport.date = date
            sport.sport_type = sport_type
            sport.save()

            return redirect('sports:sport_detail', sport_id=sport.pk)

    ctx = {'sport': sport}
    return render(request, 'sports/form.html', ctx)



def sport_detail(request, sport_id):
    sport = get_object_or_404(Sport, pk=sport_id)
    ctx = {'sport': sport}
    return render(request, 'sports/detail.html', ctx)


def sport_delete(request, sport_id):
    sport = get_object_or_404(Sport, pk=sport_id)
    sport.delete()
    return redirect('sports:sport_list')

templates/sports/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ sport.name }}</title>
</head>
<body>
    <h1>{{ sport.name }}</h1>

    <h3>Location: {{ sport.location }}</h3>
    <h3>Release Year: {{ sport.date }}</h3>
    <h3>Sport Type: {{ sport.sport_type }}</h3>

    <button><a href="{{ sport.get_update_url }}">Update</a></button>

    <button><a href="{% url 'sports:sport_delete' sport_id=sport.pk %}">Delete</a></button>

    <button><a href="{% url 'sports:sport_list' %}">Back to List</a></button>

</body>
</html>

templates/sports/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if sport %} Update Sport Event {% else %} Create Sport Event {% endif %}</title>
</head>
<body>
    <h1>{% if sport %} Update Sport Event {% else %} Create Sport Event {% endif %}</h1>

    {% if sport %}
        <button>
            <a href="{{ sport.get_detail_url }}">Back to Detail</a>
        </button><br><br>
    {% else %}
        <button>
            <a href="{% url 'sports:sport_list' %}">Back to List</a>
        </button><br><br>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        <label for="name">Event Name:</label><br>
        <input type="text" name="name" id="name" value="{{ sport.name }}"><br><br>

        <label for="location">Location:</label><br>
        <input type="text" name="location" id="location" value="{{ sport.location }}"><br><br>

        <label for="date">Event Date:</label><br>
        <input type="date" name="date" id="date" value="{{ sport.date }}"><br><br>

        <label for="sport_type">Sport Type:</label><br>
        <input type="text" name="sport_type" id="sport_type" value="{{ sport.sport_type }}"><br><br>

        <button type="submit">{% if sport %} Update {% else %} Create {% endif %}</button>
    </form>
</body>
</html>

templates/sports/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Sport Events</title>
</head>
<body>
    <h1>List of Sport Events</h1>

    <button>
        <a href="{% url 'home' %}">Back to Home</a>
    </button>

    <button>
        <a href="{% url 'sports:create_sport' %}">Add a New Sport</a>
    </button>

    {% for sport in sports %}
        <a href="{% url 'sports:sport_detail' sport_id=sport.pk %}"><h3>{{ sport.name }}</h3></a>
    {% empty %}
        <h3>No Sport Event</h3>
    {% endfor %}

</body>
</html>