config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('movies/', include('movies.urls')),
    path('musics/', include('musics.urls')),
    path('sports/', include('sports.urls')),
    path('travels/', include('travels.urls')),
]

travels/urls.py
from django.urls import path
from . import views


app_name = 'travels'


urlpatterns = [
    path('list/', views.travel_list, name='list'),
    path('create/', views.travel_create, name='create'),
    path('detail/<int:travel_id>/', views.travel_detail, name='detail'),
    path('delete/<int:travel_id>/', views.travel_delete, name='delete'),
    path('update/<int:travel_id>/', views.travel_update, name='update')
]

travels/models.py
from django.db import models
from django.shortcuts import reverse


class Travel(models.Model):
    destination_name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    popular_season = models.CharField(max_length=100)


    def get_detail_url(self):
        return reverse('travels:detail', args=[self.pk])


    def get_delete_url(self):
        return reverse('travels:delete', args=[self.pk])


    def get_update_url(self):
        return reverse('travels:update', args=[self.pk])

travels/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Travel


def travel_list(request):
    travels = Travel.objects.all()
    ctx = {'travels': travels}
    return render(request, 'travels/list.html', ctx)


def travel_create(request):
    if request.method == 'POST':
        destination_name = request.POST.get('destination_name')
        country = request.POST.get('country')
        description = request.POST.get('description')
        popular_season = request.POST.get('popular_season')
        if destination_name and country and description and popular_season:
            Travel.objects.create(
                destination_name = destination_name,
                country = country,
                description = description,
                popular_season = popular_season

            )
            return redirect('travels:list')
    return render(request, 'travels/form.html')


def travel_detail(request, travel_id):
    travel = get_object_or_404(Travel, pk=travel_id)
    ctx = {'travel': travel}
    return render(request, 'travels/detail.html', ctx)


def travel_delete(request, travel_id):
    travel = get_object_or_404(Travel, pk=travel_id)
    travel.delete()
    return redirect('travels:list')


def travel_update(request, travel_id):
    travel = get_object_or_404(Travel, pk=travel_id)
    if request.method == 'POST':
        destination_name = request.POST.get('destination_name')
        country = request.POST.get('country')
        description = request.POST.get('description')
        popular_season = request.POST.get('popular_season')
        if destination_name and country and description and popular_season:
            travel.destination_name = destination_name
            travel.country = country
            travel.description = description
            travel.popular_season = popular_season
            travel.save()
            return redirect(travel.get_detail_url())
    ctx = {'travel': travel}
    return render(request, 'travels/form.html', ctx)

templates/travels/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ travel.destination_name }}</title>
</head>
<body>
    <h1>{{ travel.destination_name }}</h1>

    <h3>Country: {{ travel.country }}</h3>
    <h3>Description: {{ travel.description }}</h3>
    <h3>Popular Season: {{ travel.popular_season }}</h3>

    <button><a href="{{ travel.get_update_url }}">Update</a></button>
    <button><a href="{{ travel.get_delete_url }}">Delete</a></button>
     <button><a href="{% url 'travels:list' %}">Back to List</a></button>
</body>
</html>

templates/travels/form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% if travel %}Update Travel Destination {% else %}Create Travel Destination{% endif %}</title>
</head>
<body>
    <h1>{% if travel %}Update Travel Destination {% else %}Create Travel Destination{% endif %}</h1>

        {% if travel %}
            <button>
                <a href="{{ travel.get_detail_url }}" >Back to Detail</a>
            </button><br><br>
        {% else %}
            <button>
                <a href="{% url 'travels:list' %}">Back to List</a>
            </button><br><br>
        {% endif %}

    <form method="post">
        {% csrf_token %}

        <label for="destination_name">Destination Name</label><br>
        <input type="text" id="destination_name" name="destination_name" value="{{ travel.destination_name }}"><br><br>

        <label for="country">Country</label><br>
        <input type="text" id="country" name="country" value="{{ travel.country }}"><br><br>

        <label for="description">Description</label><br>
        <textarea id="description" name="description" rows="5" cols="50" value="{{ travel.description }}"></textarea><br><br>

        <label for="popular_season">Popular Season</label><br>
        <input type="text" id="popular_season" name="popular_season" value="{{ travel.popular_season }}"><br><br>

        <button type="submit">{% if travel %}Update {% else %}Create{% endif %}</button>
    </form>
</body>
</html>

templates/travels/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Travel Destinations</title>
</head>
<body>
    <h1>Travel Destinations</h1>

    <a href="{% url 'home' %}"><button>Back to Home</button></a>
    <a href="{% url 'travels:create' %}"><button>Create Destination</button></a>

    {% for travel in travels %}
        <a href="{% url 'travels:detail' travel.id %}">
            <h3>{{ travel.destination_name }}</h3>
        </a>
    {% empty %}
        <h3>No Travel Destinations</h3>
    {% endfor %}
</body>
</html>