config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('movies/', include('movies.urls')),
    path('musics/', include('musics.urls')),
    path('sports/', include('sports.urls')),
    path('travels/', include('travels.urls')),
]

musics/urls.py
from django.urls import path
from . import views


app_name = 'musics'


urlpatterns = [
    path('list/', views.music_list, name='music_list'),
    path('create/', views.create_music, name='create_music'),
    path('update/<int:music_id>/', views.update_music, name='update_music'),
    path('detail/<int:music_id>/', views.music_detail, name='music_detail'),
    path('delete/<int:music_id>/', views.music_delete, name='music_delete'),
]

musics/models.py
from django.db import models
from django.urls import reverse


class Music(models.Model):
    album_title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    date = models.DateField()
    genre = models.CharField(max_length=50)


    def get_detail_url(self):
        return reverse('musics:music_detail', args=[self.pk])


    def get_delete_url(self):
        return reverse('musics:music_delete', args=[self.pk])


    def get_update_url(self):
        return reverse('musics:update_music', args=[self.pk])

musics/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Music


def music_list(request):
    musics = Music.objects.all()
    ctx = {'musics': musics}
    return render(request, 'musics/list.html', ctx)


def create_music(request):
    if request.method == "POST":
        album_title = request.POST.get('album_title')
        artist = request.POST.get('artist')
        date = request.POST.get('date')
        genre = request.POST.get('genre')
        if album_title and artist and date and genre:
            Music.objects.create(
                album_title=album_title,
                artist=artist,
                date=date,
                genre=genre,
            )
            return redirect('musics:music_list')
    return render(request, 'musics/form.html')


def update_music(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    if request.method == 'POST':
        album_title = request.POST.get('album_title')
        artist = request.POST.get('artist')
        date = request.POST.get('date')
        genre = request.POST.get('genre')
        if album_title and artist and date and genre:
            music.album_title = album_title
            music.artist = artist
            music.date = date
            music.genre = genre
            music.save()
            return redirect(music.get_detail_url())
    ctx = {'music': music}
    return render(request, 'musics/form.html', ctx)

def music_detail(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    ctx = {'music': music}
    return render(request, 'musics/detail.html', ctx)


def music_delete(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    music.delete()
    return redirect('musics:music_list')

templates/musics/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{music.album_title}}</title>
</head>
<body>
    <h1>{{music.album_title}}</h1>

    <h3>Artist: {{sport.artist}}</h3>
    <h3>Release Year: {{music.date}}</h3>
    <h3>Genre: {{music.genre}}</h3>

    <button>
        <a href="{{ music.get_update_url }}">Update</a>
    </button>

    <button>
        <a href="{% url 'musics:music_delete' music_id=music.pk %}">Delete</a>
    </button>

    <button>
        <a href="{% url 'musics:music_list' %}">Back to Album</a>
    </button>

</body>
</html>

templates/musics/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if music %} Update Album {% else %} Create Album {% endif %}</title>
</head>
<body>
    <h1>{% if music %} Update Album {% else %} Create Album {% endif %}</h1>

    {% if music %}
        <button>
            <a href="{{ music.get_detail_url }}">Back to Detail</a>
        </button><br><br>
    {% else %}
        <button>
            <a href="{% url 'musics:music_list' %}">Back to List</a>
        </button><br><br>
    {% endif %}

    <form method="post"><br>
        {% csrf_token %}

        <label for="album_title">Album Title:</label><br>
        <input type="text" name="album_title" id="album_title" value="{{ music.album_title }}"><br><br>

        <label for="artist">Artist:</label><br>
        <input type="text" name="artist" id="artist" value="{{ music.artist }}"><br><br>

        <label for="date">Release Date:</label><br>
        <input type="date" name="date" id="date" value="{{ music.date }}"><br><br>

        <label for="genre">Genre:</label><br>
        <input type="text" name="genre" id="genre" value="{{ music.genre }}"><br><br>

        <button type="submit">{% if music %} Update {% else %} Create {% endif %}</button>
    </form>
</body>
</html>

templates/musics/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Musics</title>
</head>
<body>
    <h1>List of Musics</h1>

    <button>
        <a href="{% url 'home' %}">Back to Home</a>
    </button>
    <button>
        <a href="{% url 'musics:create_music' %}">Add a New Album</a>
    </button>

    {% for music in musics %}
        <a href="{% url 'musics:music_detail' music_id=music.pk %}"><h3>{{ music.album_title }}</h3></a>
    {% empty %}
        <h3>No Music</h3>
    {% endfor %}

</body>
</html>